#!/usr/bin/env node

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(fileURLToPath(new URL('..', import.meta.url)))
const sourceRoot = resolve(root, 'config/agent-presets')
const generatedRoot = resolve(root, 'generated/agent-presets')
const mode = process.argv[2] ?? '--check'

function files(directory) {
  const result = []
  for (const entry of readdirSync(directory, { withFileTypes: true, recursive: true })) {
    if (entry.isFile()) result.push(relative(directory, resolve(entry.parentPath, entry.name)))
  }
  return result.sort()
}

function check() {
  const sourceFiles = files(sourceRoot)
  const generatedFiles = existsSync(generatedRoot) ? files(generatedRoot) : []
  const failures = []
  if (JSON.stringify(sourceFiles) !== JSON.stringify(generatedFiles)) {
    failures.push(`file set drift: source=${sourceFiles.join(',')} generated=${generatedFiles.join(',')}`)
  }
  for (const file of sourceFiles) {
    const generated = resolve(generatedRoot, file)
    if (!existsSync(generated) || !readFileSync(resolve(sourceRoot, file)).equals(readFileSync(generated))) {
      failures.push(`${file}: generated bytes differ from source`)
    }
  }
  if (failures.length > 0) {
    for (const failure of failures) process.stderr.write(`preset check: ${failure}\n`)
    return 1
  }
  process.stdout.write(`preset drift check passed (${sourceFiles.length} files)\n`)
  return 0
}

if (mode === '--generate') {
  rmSync(generatedRoot, { recursive: true, force: true })
  mkdirSync(dirname(generatedRoot), { recursive: true })
  cpSync(sourceRoot, generatedRoot, { recursive: true })
  process.stdout.write(`generated presets from config/agent-presets\n`)
} else if (mode === '--check') {
  process.exitCode = check()
} else {
  throw new Error('usage: node scripts/check-presets.mjs [--check|--generate]')
}
